### ISSUE TITLE
Get an error when using bands_Si.py as template to plot my system

### ISSUE THREAD

**Issue by uwhbliu** [gVallverdu/bandstructureplots#1]
Hi Germain,
Thank you for your code!
I used your bands_Si.py as template to plot the DOS and band structure for my system. 
I ran into an Error that : 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/hbliu/plot_bandos_test.py in <module>()
     83     for b in range(bands.nb_bands):
     84         for k in range(len(bands.kpoints)):
---> 85             sc = pbands[Spin.up][b][k][name]["s"]**2
     86             pc = pbands[Spin.up][b][k][name]["p"]**2
     87             dc = pbands[Spin.up][b][k][name]["d"]**2
KeyError: <Spin.up: 1>
```

Do you have any idea to fix this error? Thank you so much!

**Comment by uwhbliu** [comment]
Hi Germain,
I just compared my INCAR with yours, I found that in the INCAR of Bandes, you also specify the LORBIT = 11, so you have more detailed DOSCAR. I haven't specify LORBIT in my INCAR of Bandes, will that be the reason I got the error? Thank you!

**Comment by gVallverdu** [comment]
Hi
Yes it is probably the origin of you error. If you don't set LORBIT = 11, projected DOS are not printed in DOSCAR.
Give it a try and let me know.
Germain

**Comment by uwhbliu** [comment]
Hi Germain,
Thank you so much for your patient reply, adding LORBIT =11 do fix the problem! I also have something to ask about the bandstructure.py script, I will open another issue.
