### ISSUE TITLE
Problems with outdated modules 

### ISSUE THREAD

**Issue by DagMj** [gVallverdu/bandstructureplots#11]
Dear Vallverdu, 

I am trying to follow your template "bands_Si.py" to plot my bandstructures and DOS calculated with VASP but i keep running into problems because of outdated modules. Is a similar template with the newest modules of pymatgen available?   Any help or pointers will be greatly appreciated.

Best regards,

**Comment by gVallverdu** [comment]
Hello
I did an update of the scripts. Now it should works with the current pymatgen version.
