### ISSUE TITLE
Energy Range Problem

### ISSUE THREAD

**Issue by abduljalils** [gVallverdu/bandstructureplots#12]
Dear Users
I want to plot bandstructure and DOS in the specific range. I have changed the value code as given below,but it does not effect on plot,Secondly I also want to delete the gap between DOS and Bandstructure diagram.please suggest solution.
Thanks in Advance
 ```py
emin =5. 
emax =-5.
for spin in bands.bands.keys():
    for b in range(bands.nb_bands):
        emin = min(emin, min(bands.bands[spin][b]))
        emax = max(emax, max(bands.bands[spin][b]))

emin -= bands.efermi + 1
emax -= bands.efermi - 1

ax1.set_ylim(emin, emax)
ax2.set_ylim(emin, emax)
```
![image](https://user-images.githubusercontent.com/19342123/40040942-daff41da-584e-11e8-8aaa-dda9bbbc5c5e.png)

**Comment by gVallverdu** [comment]
Dear Abdul
Actually, the code try to determine emin and emax as you can see in the lines you wrote in your comment.
If you want to manually define the energy range, comment or remove the line and put your own values.

**Comment by abduljalils** [comment]
got,thank you.How can we get help other modules of pymatgen .i want to
calculate polarization and thermoelectric properties using boltztrap.




*ABDUL JALILLecturerDepartment of Physics00923315192550,0519057214*
*Allama Iqbal Open university,** Islamabad Pakistan.*
*http://www.aiou.edu.pk/ <http://www.aiou.edu.pk/>*

**Comment by abduljalils** [comment]
Thank excellent code!everything is looking fine but please how can we
change the position of fancy box? I want to draw at to position.Also wants
to change text style.






*ABDUL JALILLecturerDepartment of Physics00923315192550,0519057214*
*Allama Iqbal Open university,** Islamabad Pakistan.*
*http://www.aiou.edu.pk/ <http://www.aiou.edu.pk/>*

**Comment by abduljalils** [comment]
Sorry forget to mention, its nanotube the calculated bandstructure is
along(GAMMA to Z) how can i remove the x and M lines?




*ABDUL JALILLecturerDepartment of Physics00923315192550,0519057214*
*Allama Iqbal Open university,** Islamabad Pakistan.*
*http://www.aiou.edu.pk/ <http://www.aiou.edu.pk/>*
