### ISSUE TITLE
How to plot the band structure for specific orbital?

### ISSUE THREAD

**Issue by ashiskundu** [gVallverdu/bandstructureplots#2]
Hi,

I have run the script successfully. Thank you for this nice script. I have few questions..
1) In case of spin-polarization, How to plot bands for both spin(spin up and spin down)?

2) I am interested to look DOS and band structure near Fermi level. How can I specify the energy range in the plot?

3) Is is possible to plot the band structure with specific orbital(like the DOS of d_xy, d_yz……or t_2g and e_g)?

**Comment by gVallverdu** [comment]
Hi

#### Question 1

Yes but you have to do the job. I will update as soon as possible a new python module with easy functions to do that, but it is still not achieve. In the meantime, you can look at this notebook about [MnO](http://nbviewer.jupyter.org/github/gvallverdu/cookbook/blob/master/plotly_bandDiagram_SpinPolarized.ipynb) but here I use plotly to do the plot.

#### Question 2

If you look at, for example, Cu_bands/bands_Cu.py at line 62

``` py
# set ylim for the plot
# ---------------------
emin = -10.
emax = 10.
```

Variables, `emin` and `emax` set the range of y axes.

#### Question 3

Yes, you can but you have to use `Procar.data` attribute from the  [Procar](http://pymatgen.org/pymatgen.io.vasp.html#pymatgen.io.vasp.outputs.Procar)
 object of pymatgen. Look at graphene/graphene.py for example.

``` py
# projected bands
data = Procar("./bands/PROCAR").data
```

For example, you can then get one coefficient with : 

``` py
data[k][b][Orbital.py.value]
```

where `k` and `b` are over kpoints and bands respectively.
