### ISSUE TITLE
Two warnings 

### ISSUE THREAD

**Issue by sepplhans** [gVallverdu/bandstructureplots#3]
Hi, 
im evaluating my DFT calculation from vasp with your plotting python script.
When im executing i receive two warnings:

```
/usr/local/lib/python2.7/dist-packages/pymatgen/io/vasp/outputs.py:543: UserWarning: Final e_wo_entrp differs from the final electronic step. VASP may have included some corrections, e.g., vdw. Vasprun will return the final e_wo_entrp, i.e., including corrections in such instances.
  warnings.warn("Final e_wo_entrp differs from the final "

/usr/lib/pymodules/python2.7/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':
```

What can i do to avoid that warnings? 

Nevertheless the PDOS and Bandstructure are looking good.

Thanks for your great work!

**Comment by gVallverdu** [comment]
Hello
These warnings do not come from my script. The first is a pymatgen warning and the second a matplotlib ones.

Considering the first about energy without entropy. Look at your calculation. Did you use a VdW correction ? I do not use `final_energy` in my scripts. What are you looking for ?

I see that you are using python2.7. Maybe the matplotlib warnings comme from here. Is this all the output or does python say which line of my script gives you that warnings ?

**Comment by sepplhans** [comment]
Yes, i used vdW correction (DFT-D3 Method).
I want to plot the band-structure beside the DOS-plot of my simulated unit cell.
thank you for your help!
