### ISSUE TITLE
Distance between k-points

### ISSUE THREAD

**Issue by Rinochek** [gVallverdu/bandstructureplots#4]
Dear Germain,
Thank you very much for your code. 
Don't you know yet, how to make different distances between k-points?
Where could be find an information about?
Thank you very much!

**Comment by gVallverdu** [comment]
Dear Rinocheck,
I guess you want to have the distance between k-points adapted to the reciprocal lattice. That is true that the current code does not support that.

If you look at the [BSPlotter](http://pymatgen.org/pymatgen.electronic_structure.html#module-pymatgen.electronic_structure.plotter) class of pymatgen you can extract the xcoords from for example  : 

``` py
bsplot = BSPlotter(bands)
plotdata = bsplot.bs_plot_data(zero_to_efermi=True)
lines = plotdata["distances"]
```

where `bands` is a ban_structure object of pymatgen.

The following version of my code will support that. I will commit it soon... I hope.

Germain

**Comment by Rinochek** [comment]
Thank you!
I wish you successfully commit it! ;)
