### ISSUE TITLE
About figure

### ISSUE THREAD

**Issue by Huta2018** [gVallverdu/bandstructureplots#6]
Hello Germain,

Thank you so much for such a nice script. I can run it and get plots. I have small question about image format.
When I run it on cluster and save the image as .pdf, .jpg or any other supported format, and move it to my local computer , I cannot see my Image, it appears blank.

Here I have attached files as they appear.

Thanks in advance.

![band_structure_mos2](https://cloud.githubusercontent.com/assets/20651804/23043483/6d24bba2-f46a-11e6-91e8-5e66c34c6fd1.png)
![band_plot](https://cloud.githubusercontent.com/assets/20651804/23043487/731c9e4e-f46a-11e6-8210-7fede5c60c8b.png)

**Comment by Huta2018** [comment]
This is how it appears if  I save but when I try to open one saved by using script, it appears blank.

**Comment by Huta2018** [comment]
I had a same problem before. Actually there may be two things, either you missed to import from matplotlib.backends.backend_pdf import PdfPages  or you save to your pdf file after you close pdf.

**Comment by gVallverdu** [comment]
I am not really familiar with matplotlib backends but thank you for the comments.

Moreover, it seems that you have a really small number of k-points on each line. The issue may come from that point. Finally, you could simply try to adjust the `xlim` in order to fix the output.
