### ISSUE TITLE
pdos and tdos

### ISSUE THREAD

**Issue by AmirNi2016** [gVallverdu/bandstructureplots#7]
Hi,

Why is not the sum of projected DoS for s, pxpy and pz equal to the total DoS data? It is expecially clear near the cone here:
https://github.com/gVallverdu/bandstructureplots/blob/master/graphene/graphene.png

Cheers

**Comment by gVallverdu** [comment]
Hi
there are maybe two origin of this : 
* first VASP is a plane wave code, thus projections in AO is not completely safe as you can loose a piece of density or have a double counting of it in some regions.
* second, calculation I did for the graphene here is not really accurate. It is just a toy for a student example. The aim was essentially to identify sigma and pi bands.

Regards
